### PR TITLE
Fix url resolve

### PR DESCRIPTION
**Pull request by kristojorg**
We previously used the legacy `resolve` method from node's `url` module in the `OPDSDataAdapter`. This caused certain nested urls to be improperly resolved. This PR updates the adapter to use the new URL module, which properly resolves the urls. 

It has been tested in circulation-patron-web.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Cool, this is fine but can you update the version so I can publish a new version? Also,

**Comment by kristojorg** [comment]
Yep, done along with changelog!

**Comment by kristojorg** [comment]
Turns out I also forgot to update the changelog in 0.5.0 (#271 ). I added an item for it in this PR.

**Comment by EdwinGuzman** [comment]
Published.

**Pull request merged**
