### PR TITLE
add devtools extension

### PR DESCRIPTION
**Pull request by kristojorg**
This adds the ability for the Redux Devtools browser extension to log actions and store updates.

The extension is here: https://github.com/zalmoxisus/redux-devtools-extension

This shouldn't actually add any code weight to the package. It just checks if the extension is available on the window and calls it if so. The NPM package added is mainly typescript typings.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Can you fix the merge conflicts so I can publish 0.5.2?

**Comment by kristojorg** [comment]
Okay I resolved the conflict, should be good to go!

**Comment by kristojorg** [comment]
Done! If one of you doesn't mind merging that would be great

**Comment by M0nica** [comment]
@EdwinGuzman can you merge this PR? I don't have merging permission.

**Comment by EdwinGuzman** [comment]
Done and published.

**Pull request merged**
